account/urls.py
import imp
from unicodedata import name
from django.urls import path, re_path
from .views import *
app_name = "account"
urlpatterns = [   
    path ("blogs/", all_blogs_view, name = "blogs_view"),
    path("<int:id>/", single_blog_view , name="view_single_blog"),   
]

article/urls.py
from unicodedata import name
from django.urls import path, re_path
from .views import *
app_name = "article"
urlpatterns = [
    path("", article, name="article" ),
    path("post/add", post_article, name="post_article"),
    #path("post/edit", edit_article, name="edit_article_post"),
    path("<int:id>/article_detail", article_details, name="article_details"), 
    path("tag/<str:tagname>/", tag_name, name="tag_name" ),  
]

blogcast/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from account.views import signup,login
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
urlpatterns = (
    [
    path('admin/', admin.site.urls),
    path('user/', include('account.urls')),
    path('articles/', include('article.urls')),
    path("signup", signup, name="signup"), 
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    #path("accounts/login", login, name="login"), 
    path('', views.index, name = "index" ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
   # path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('blog/', include('blog.urls')),
    #path('api/v1/', include('blog.api.v1.routers.routers')), 
    #path("podcast/", include('podcast.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    
    <title>{% block title %} Blogalways {% endblock %} </title>

</head>
<body>
    {% include "topnav.html" %}
    {% block content %}
    
    {% endblock %}
    {% block footer%}
    <section>
        <div class="footer fixed-bottom bg-dark text-white">
           <div class="text-center"> Email: info@blogalways.com</div>
           <div class="text-center"> &copy; Copyright 2022</div>
        </div>
    </section>
    {% endblock%}
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}BlogAlways{% endblock title %}
{% block content %}

  
 
<!-- /* Show Case */ -->
<section class="bg-dark text-light p-5 p-lg-0 pt-lg-5 text-center text-sm-start">
    <div class="container">
        <div class="d-sm-flex ">
            <div class="">
                <h1>
                    Free Your Ideas <span class="text-warning" >Share, Empower, Inspire</span> 
                </h1>
                <p class="lead my-5">
                    Write or record  your thoughts on any topic  and connect with millions of readers and listeners world wide. <br> It's free and easy
                </p>
                {% comment %} <a href="{% url 'user:signup' %}" class="btn btn-primary btn-lg"></a> {% endcomment %}
                <a li class="btn btn-primary btn-lg" href="{% url 'signup' %}">Get Started</a li>
            </div>
          
                <img src="{% static '/images/writer.svg' %}" alt="image of someone typing on pc" class="img-fluid w-50 d-none d-sm-block">           
        </div>
    </div>
</section>
<!-- Newsletter -->
<section class="bg-primary text-light p-5">
    <div class="container">
        <div class="d-md-flex align-items-center justify-content-between">
            <h3 class="mb-3 mb-md-0">
                Sign up for Our Newsletter
            </h3>
            <div class="input-group news-input">
                <input type="text" class="form-control" placeholder="Enter Email address">
                <button class="btn btn-dark btn-lg" type="button">Subscribe</button>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/topnav.html
  <!-- Navbar -->
 <nav class="navbar navbar-expand-lg bg-dark navbar-dark">  
  <div class="container"> 
      <a href="{% url 'index' %}" class="navbar-brand">Blog Always</a>
  
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navmenu">

      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
            <a href="{% url 'account:blogs_view' %}" class="nav-link">Blogs </a>
        </li>
         <li class="nav-item">
             <a href="{% url 'article:article' %}" class="nav-link">Articles </a>
         </li>
         <li class="nav-item">
          <a href="#questions" class="nav-link"> Podcast</a>
      </li>
      <li class="nav-item">
        <a href="#instructors" class="nav-link"> Nuggets</a>
    </li>
      <li class="nav-item">
          <a href="#instructors" class="nav-link"> About Us</a>
      </li>
      </ul>
  </div>
  </div>
</nav>
<!-- End of Navbar -->