account/urls.py
import imp
from unicodedata import name
from django.urls import path, re_path
from .views import *
app_name = "account"
urlpatterns = [   
    path ("blogs/", all_blogs_view, name = "blogs_view"),
    path("<int:id>/", single_blog_view , name="view_single_blog"),   
]

article/urls.py
from unicodedata import name
from django.urls import path, re_path
from .views import *
app_name = "article"
urlpatterns = [
    path("", article, name="article" ),
    path("post/add", post_article, name="post_article"),
    #path("post/edit", edit_article, name="edit_article_post"),
    path("<int:id>/article_detail", article_details, name="article_details"), 
    path("tag/<str:tagname>/", tag_name, name="tag_name" ),  
]

blogcast/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from account.views import signup,login
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
urlpatterns = (
    [
    path('admin/', admin.site.urls),
    path('user/', include('account.urls')),
    path('articles/', include('article.urls')),
    path("signup", signup, name="signup"), 
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    #path("accounts/login", login, name="login"), 
    path('', views.index, name = "index" ),
    path('ckeditor/', include('ckeditor_uploader.urls')),
   # path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('blog/', include('blog.urls')),
    #path('api/v1/', include('blog.api.v1.routers.routers')), 
    #path("podcast/", include('podcast.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

article/models.py
from pyexpat import model
from unicodedata import category
from django.db import models
from django.forms import ChoiceField, DateTimeField
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from matplotlib.image import thumbnail
User = get_user_model()
# Create your models here.


class Category(models.Model):
    category = models.CharField(max_length = 255, name = "category")
    def __str__(self):
        return self.category
    
class HashTag(models.Model):
    tagname1 = models.CharField(max_length = 255, name = "tagname1")
    def __str__(self):
        return self.tagname1

class Articles(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name ="author2")
    title = models.CharField(max_length = 255, name= "title")
    date = models.DateTimeField(auto_now_add = True)
    thumbnail = models.ImageField( upload_to="articles/thumbnail/")
    content = RichTextUploadingField()
    # image2 = models.ImageField( upload_to="articles/thumbnail/",  null=True, blank= True)
    # content_part2 = RichTextField(null = True, blank= True)
    # image3 = models.ImageField( upload_to="articles/thumbnail/", null=True, blank= True)
    # content_part3 = RichTextField(null = True, blank= True)
    # image4 = models.ImageField( upload_to="articles/thumbnail/" , null=True, blank= True)
    # content_part4 = RichTextField(null = True, blank= True)
    # image5 = models.ImageField( upload_to="articles/thumbnail/" ,  null=True, blank= True)
    # content_part5 = RichTextField( null = True, blank= True)
    # image6 = models.ImageField( upload_to="articles/thumbnail/" , null=True, blank= True)
    # content_part6 = RichTextField(null = True, blank= True)
    category =models.ForeignKey(Category, on_delete=models.PROTECT)
    hashtag  =models.ForeignKey(HashTag, on_delete=models.CASCADE, null= True, blank=True )
    
    def __str__(self):
            return self.title
    class Meta:
        ordering = ['-id']

article/forms.py
from django.forms import ModelForm

from .models import *



# class CkEditorForm(forms.Form):
#     ckeditor_standard_example = RichTextFormField()
#     ckeditor_upload_example = RichTextUploadingFormField(
#         config_name="my-custom-toolbar"
#     )

    
class post_article_forms (ModelForm):
    class Meta: 
        model = Articles
        fields = ["title",
        "thumbnail", "content",
        "category",
        "hashtag",]

  # "image2", "content_part2",
        # "image3", "content_part3",
        # "image4", "content_part4",
        # "image5", "content_part5",
        # "image6", "content_part6",

article/views.py
from django.core.checks import messages
from django.contrib import messages
from importlib.metadata import files
from multiprocessing import context
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import *
from django.urls import reverse
from django.views import generic

from .forms import *


# class CkEditorFormView(generic.FormView):
#     form_class = forms.CkEditorForm
#     template_name = "article/post_article.html"
#     def get_success_url(self):
#         return reverse("ckeditor-form")

# ckeditor_form_view = CkEditorFormView.as_view()


def article (request):
    articles = Articles.objects.all()
    tags = HashTag.objects.all()
    #search
    search_item = request.GET.get('search_item')
    if search_item != '' and search_item != None:
        articles = articles.filter(title__icontains = search_item)
    context = {
        "articles":articles,
        "tags": tags,
    }
    return render(request, "article/articles.html", context)
    
def index (request):
    return render (request, "index.html")

def tag_name(request, tagname):

    return render(request, "article/tag_page.html", {
        "tagname":tagname,
    })

def article_details(request, id):
    article = get_object_or_404(Articles, id = id)
   
    content ={
        "articles": article,
    }
    return render (request, "article/article_details.html", content)

@login_required
def post_article(request):
    if request.method == "POST":
        postarticleforms = post_article_forms(data= request.POST, files=request.FILES)
        if postarticleforms.is_valid():
            postarticle =  postarticleforms.save(commit=False)
            print("was able to take the date")
            postarticle.author = request.user
            postarticle.save()
            messages.success(request, 'Post Created')
            return redirect("/articles/")
        else:
            messages.warning(request, "Invalid data entry")
    else: 
        
        postarticleforms = post_article_forms()
        print("nothing came out")
    context ={
        "postarticleforms": postarticleforms,
    }
    return render(request, "article/post_article.html", context)

templates/article/article_details.html
{% extends "base.html" %}


{% block content %}

<div class="container">
    <div class="row">
        <hr>
        <img src="{{articles.author.profile.profile_picture.url}}" alt = "user_profile not set"  height ="100px" style=" width:100px;height:100px; border-radius: 50%">
        <i> Author:  {{articles.author.profile.firstName}} {{articles.author.profile.lastName}}   was published on {{articles.date}} </i>
        <hr>
    </div>

    <div class="col-12 py-5">
        <div class="md-5 w-100">
            <div class="row g-0">
                <h1 class="card-title">{{articles.title}} </h1>
              
                <div class="col-md-12">
                    <img src="{{articles.thumbnail.url}}" alt="Image not Found" width="12800"  class=" detail_image" height='10%'>
                </div>
                <div class="row g-0">                    
                    <p class="card-text" >
                        {{articles.content | safe}}
                    </p>

                </div>
            </div>  
        </div>        
</div>

{% endblock content %}

templates/article/articles.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Articles{% endblock title %}

{% block content %}


<div class="container">
  <!-- This row contains the search bar -->
  <div class="row py-3" >
    <div class="col-md-2 my-2 align-item-center" > <a href="{% url 'article:post_article'%}" class="btn btn-primary">Start Writing</a> <!-- Search Functionality -->                 
    </div>
    <div class="col-md-10"> 
         <!-- Another variation with a button -->
      <form >
        <div class="input-group">
          <input type="text" name="search_item" class="form-control" placeholder="Search this blog">
          <div class="input-group-append">
            <button class="btn btn-secondary" type="submit">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
              </svg>
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- this row contains the main content -->
  <div class="row">
    <div class= "col-md-8">
      <div class="row">
        {% for article in articles %}
        
        <div class="col-lg-6 p-2 border"> 
          <div class="row" >
            <div class="col-8 border-primary">
              <div class="row border-danger">    <!-- this is the user-->
                <div class="col-md-12"><a href="{% url 'account:view_single_blog' article.author.id %}" style="text-decoration:none"> <img src="{{article.author.profile.profile_picture.url}}" width="20" height="20" class="img-fluid" style="border-radius:50%"> <span class="col-md-3" style="font-size:0.6em; "> <i>{{article.author.profile.firstName}} {{article.author.profile.lastName}}</i></span></a>
                </div>
              </div>           <!-- this is the user-->
              
                <div class="row">  <!-- article title-->
                  <div class= "col-md-12"> <h6> <b><a href="{% url 'article:article_details' article.id %}" style="text-decoration:none; color:black;">{{article.title}}</a></h6> </b> 
                  </div>            
                </div>

                <div class="row" >
                  <div class= "col-md-12 discription"> <p> {{article.content | safe |truncatewords:12}}</div> 
                </div>
                <div class="row">
                      <div class="col-md-12"> <span class="col-md-3" style="font-size:0.6em; "> <b> {{article.category}} </b></span><span class="col-md-3 px-3 text-align-end" style="font-size:0.6em;text-align: end; ">{{ article.date}}</span>
                      </div>
                </div>
              
            </div>
           
              <div class="col-4  px-1">
                <div class="row">
                  <img src="{{article.thumbnail.url}}" class="img-fluid" width="120" height="120" object-fit: cover>
                </div>
              </div>
          
          </div>
        </div>
        {% endfor %}
      </div> 
    </div>
   
    <div class ="col-md-4 tags"> 
          {% for tag in tags %}
          <span><a href="tag/{{tag.tagname1}}"  style="text-decoration: none;">{{tag.tagname1}} </a> </span>
          {% endfor %}
        </div>
    
  </div>
</div>
{% endblock content %}

templates/article/post_article.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Write an Article
{% endblock title %}
{% block content %}
<div class="container">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <div class="row">
        <div class="col-4">
......................................
        </div>
        <div class="col-md-4">
            <h2 class="text-center text-bolder">Write an Article</h2>
            <small class="text-center"> fields marked (*) are mandatory </small>
            <hr>
            <form method="POST" action="{% url 'article:post_article' %}?next=/"  enctype="multipart/form-data">
                {% csrf_token %}
                {{postarticleforms.media}}
                {{postarticleforms}}
                <p><input class="btn btn-success" type="submit" value="Publish"></p>

            </form>
        </div>
        <div class ="col-md-4">
            ...........................
        </div> 
    </div>

</div>
    {% comment %} <form method="POST" action="./">
        {{ form.errors }}
        {% csrf_token %}
        {{ form.media}}

        {{ form.non_field_errors }}
<div class="fieldWrapper">
    {{ form.title.errors }}
    <span>{{ postarticleforms.title.label_tag}}</span>
    {{ postarticleforms.title }}
</div>


<div class="imagefieldWrapper1">
    {{ postarticleforms.image1.errors }}
    <span>{{ postarticleforms.image1.label_tag}}(Thumbnail)</span>
    {{ postarticleforms.image1 }}
</div>
<div class="textfieldWrapper1">
    {{ postarticleforms.content_part1.errors }}
    <span> {{ postarticleforms.content_part1.label_tag}} </span>
    {{ postarticleforms.content_part1 }}
</div>

<div id="imagefieldWrapper2" >
    {{ postarticleforms.image2.errors }}
    <span>{{ postarticleforms.image2.label_tag}}</span>
    {{ postarticleforms.image2 }}
</div>
<div id="textfieldWrapper2" >
    {{ postarticleforms.content_part2.errors }}
    <span>{{ postarticleforms.content_part2.label_tag}}</span>
    {{ postarticleforms.content_part2 }}
</div>

<div id="imagefieldWrapper3" >
    {{ postarticleforms.image3.errors }}
    <span>{{ postarticleforms.image3.label_tag}}</span>
    {{ postarticleforms.image3 }}
</div>
<div id="textfieldWrapper3" >
    {{ postarticleforms.content_part3.errors }}
    <span>{{ postarticleforms.content_part3.label_tag}}</span>
    {{ postarticleforms.content_part3 }}
</div>

<div id="imagefieldWrapper4" >
    {{ postarticleforms.image4.errors }}
    <span>{{ postarticleforms.image4.label_tag}}</span>
    {{ postarticleforms.image4 }}
</div>
<div id="textfieldWrapper4" >
    {{ postarticleforms.content_part4.errors }}
    <span>{{ postarticleforms.content_part4.label_tag}}</span>
    {{ postarticleforms.content_part4 }}
</div>

<div id="imagefieldWrapper5" >
    {{ postarticleforms.image5.errors }}
    <span>{{ postarticleforms.image5.label_tag}}</span>
    {{ postarticleforms.image5 }}
</div>
<div id="textfieldWrapper5" >
    {{ postarticleforms.content_part5.errors }}
    <span>{{ postarticleforms.content_part5.label_tag}}</span>
    {{ postarticleforms.content_part5 }}
</div>

<div id="imagefieldWrapper6" >
    {{ postarticleforms.image6.errors }}
    <span>{{ postarticleforms.image6.label_tag}}</span>
    {{ postarticleforms.image6 }}
</div>
<div id="textfieldWrapper6" >
    {{ postarticleforms.content_part6.errors }}
    <span>{{ postarticleforms.content_part6.label_tag}}</span>
    {{ postarticleforms.content_part6 }}
</div>
     <p><input class="btn btn-success" type="submit" value="Post"></p>

    </form>
    <button class="btn btn-outline" onclick="addimage()"> <i class="bi bi-plus" id="img-button" >Image</i></button> <button class="btn btn-outline" onclick="addtext()" id="text-button" > <i class="bi bi-plus">Text Field</i></button>

        </div>
   </div>
</div> {% endcomment %}

<script>
    {% comment %} $(document).read(function(){
        var max_fields = 7;
        var imgwrapper2 = $(".imagefieldWrapper2")
        var txtwrapper2 = $(".textfieldWrapper2")
        var addimgbutton = $("#img-button");
        var addtxtbutton = $("#text-button");

        var x = 1; var y = 1;
        $(addimgbutton).click(function(e){
            e.preventDefault();
            if(x < max_fields){
                x++;
                $(imgwrapper2).show()
                $(".imagefieldWrapper2").css("display", "block");
               
            }
        })
        $(addtxtbutton).click(function(e){
            e.preventDefault();
            if(y < max_fields){
                y++;
                $(txtwrapper2).show();
                $(".textfieldWrapper2").css("display", "block");
            }
        })

    })
</script>
<script>
  
        var max_fields = 7;
      
        // var txtwrapper2 = $(".textfieldWrapper2")
        // var addimgbutton = $("#img-button");
        // var addtxtbutton = $("#text-button");

        var x = 1; var y = 1;
        function addimage(){
            if(x < max_fields){
              
                if (x==1) {
                    document.getElementById("imagefieldWrapper2").style.display = "block";  
                }
                if  (x ==2){
                    document.getElementById("imagefieldWrapper3").style.display = "block" ;
                } if (x==3) {
                    document.getElementById("imagefieldWrapper4").style.display = "block" ;
                } if(x==4){
                    document.getElementById("imagefieldWrapper5").style.display = "block"; 
                }
                 else if (x==5){
                    document.getElementById("imagefieldWrapper6").style.display = "block" ;
                }
                x++;
            }
        }
        function addtext(){
            if(y < max_fields){
              
                if (y==1) {
                    document.getElementById("textfieldWrapper2").style.display = "block";  
                }
                if  (y ==2){
                    document.getElementById("textfieldWrapper3").style.display = "block" ;
                } if(y==3) {
                    document.getElementById("textfieldWrapper4").style.display = "block" ;
                } if(y==4){
                    document.getElementById("textfieldWrapper5").style.display = "block"; 
                }
                 else if (y==5) {
                    document.getElementById("textfieldWrapper6").style.display = "block" ;
                }
                y++;
            }
        } 
         {% endcomment %}
</script>
{% endblock %}

templates/article/tag_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{tagname}}{% endblock title %}

{% block content %}
 All post under the tagname {{tagname}} will appear when done
{% endblock %}